//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Teams.Apps.BookAThing.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Teams.Apps.BookAThing.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to favorites.
        /// </summary>
        public static string AddFavorite {
            get {
                return ResourceManager.GetString("AddFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add favorite rooms.
        /// </summary>
        public static string AddFavTaskModuleSubtitle {
            get {
                return ResourceManager.GetString("AddFavTaskModuleSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search all rooms.
        /// </summary>
        public static string AnotherRoomTaskModuleSubtitle {
            get {
                return ResourceManager.GetString("AnotherRoomTaskModuleSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book room.
        /// </summary>
        public static string BookRoom {
            get {
                return ResourceManager.GetString("BookRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building name.
        /// </summary>
        public static string BuildingName {
            get {
                return ResourceManager.GetString("BuildingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting is cancelled by organizer using Book-a-room bot..
        /// </summary>
        public static string CancellationComment {
            get {
                return ResourceManager.GetString("CancellationComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel meeting.
        /// </summary>
        public static string CancelMeeting {
            get {
                return ResourceManager.GetString("CancelMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot add more than 15 rooms to your favorites..
        /// </summary>
        public static string CantAddMoreRooms {
            get {
                return ResourceManager.GetString("CantAddMoreRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t log you in. Please try again later..
        /// </summary>
        public static string CantLogIn {
            get {
                return ResourceManager.GetString("CantLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot recognize **{command}** as valid command. Please type &apos;Help&apos; to see all available commands..
        /// </summary>
        public static string CommandNotRecognized {
            get {
                return ResourceManager.GetString("CommandNotRecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} at {1} ({2} mins).
        /// </summary>
        public static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string DoneButton {
            get {
                return ResourceManager.GetString("DoneButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong and I can’t do that right now. Try again in a few minutes..
        /// </summary>
        public static string ExceptionResponse {
            get {
                return ResourceManager.GetString("ExceptionResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room availability is outdated. Please refresh card and try again..
        /// </summary>
        public static string Expired {
            get {
                return ResourceManager.GetString("Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That room is already one of your favorites..
        /// </summary>
        public static string FavoriteRoomExist {
            get {
                return ResourceManager.GetString("FavoriteRoomExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified favorite rooms list. Please refresh..
        /// </summary>
        public static string FavoriteRoomsModified {
            get {
                return ResourceManager.GetString("FavoriteRoomsModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not authorized to access this bot. Please contact your administrator for help..
        /// </summary>
        public static string InvalidTenant {
            get {
                return ResourceManager.GetString("InvalidTenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string LoadingMessage {
            get {
                return ResourceManager.GetString("LoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are logged in successfully!.
        /// </summary>
        public static string LoggedInSuccess {
            get {
                return ResourceManager.GetString("LoggedInSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been signed out..
        /// </summary>
        public static string LogoutSuccess {
            get {
                return ResourceManager.GetString("LogoutSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the button below to add or remove rooms from your favorites list..
        /// </summary>
        public static string ManageFavoriteCardDescription {
            get {
                return ResourceManager.GetString("ManageFavoriteCardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage favorites.
        /// </summary>
        public static string ManageFavorites {
            get {
                return ResourceManager.GetString("ManageFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting created by Book-a-room bot..
        /// </summary>
        public static string MeetingBody {
            get {
                return ResourceManager.GetString("MeetingBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room booked!.
        /// </summary>
        public static string MeetingBooked {
            get {
                return ResourceManager.GetString("MeetingBooked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting cancelled.
        /// </summary>
        public static string MeetingCancelled {
            get {
                return ResourceManager.GetString("MeetingCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting length.
        /// </summary>
        public static string MeetingLength {
            get {
                return ResourceManager.GetString("MeetingLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room booked by Book-a-room bot..
        /// </summary>
        public static string MeetingSubject {
            get {
                return ResourceManager.GetString("MeetingSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The meeting end time has elapsed..
        /// </summary>
        public static string MeetingTimeElapsed {
            get {
                return ResourceManager.GetString("MeetingTimeElapsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No favorite rooms yet. Add some for faster booking. Or, select more rooms to choose from the directory..
        /// </summary>
        public static string NoFavoriteRooms {
            get {
                return ResourceManager.GetString("NoFavoriteRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No favorite rooms yet..
        /// </summary>
        public static string NoFavoriteRoomsTaskModule {
            get {
                return ResourceManager.GetString("NoFavoriteRoomsTaskModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a room to your list of favorites to get started..
        /// </summary>
        public static string NoFavoritesDescriptionTaskModule {
            get {
                return ResourceManager.GetString("NoFavoritesDescriptionTaskModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More rooms.
        /// </summary>
        public static string OtherRooms {
            get {
                return ResourceManager.GetString("OtherRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh list.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room.
        /// </summary>
        public static string Room {
            get {
                return ResourceManager.GetString("Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added room to favorites..
        /// </summary>
        public static string RoomAddedAsFavorite {
            get {
                return ResourceManager.GetString("RoomAddedAsFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available rooms.
        /// </summary>
        public static string RoomAvailability {
            get {
                return ResourceManager.GetString("RoomAvailability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been booked successfully..
        /// </summary>
        public static string RoomBooked {
            get {
                return ResourceManager.GetString("RoomBooked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That room isn’t available. Select a different one..
        /// </summary>
        public static string RoomUnavailable {
            get {
                return ResourceManager.GetString("RoomUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchRoom {
            get {
                return ResourceManager.GetString("SearchRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type a name or location.
        /// </summary>
        public static string SearchRoomDropdownPlaceholder {
            get {
                return ResourceManager.GetString("SearchRoomDropdownPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select meeting length and room..
        /// </summary>
        public static string SelectDurationRoom {
            get {
                return ResourceManager.GetString("SelectDurationRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select room to add to your favorites..
        /// </summary>
        public static string SelectRoomToAdd {
            get {
                return ResourceManager.GetString("SelectRoomToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select time zone.
        /// </summary>
        public static string SelectTimezone {
            get {
                return ResourceManager.GetString("SelectTimezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in required.
        /// </summary>
        public static string SignInRequired {
            get {
                return ResourceManager.GetString("SignInRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time zone.
        /// </summary>
        public static string Timezone {
            get {
                return ResourceManager.GetString("Timezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The detected time zone is not supported. Please select a time zone to proceed..
        /// </summary>
        public static string TimezoneNotSupported {
            get {
                return ResourceManager.GetString("TimezoneNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I couldn&apos;t add the room to your favorites. Try again later..
        /// </summary>
        public static string UnableToAddFavorite {
            get {
                return ResourceManager.GetString("UnableToAddFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unavailable.
        /// </summary>
        public static string Unavailable {
            get {
                return ResourceManager.GetString("Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I help you to quickly book a room for your meeting on the go.
        /// </summary>
        public static string WelcomeCardContent {
            get {
                return ResourceManager.GetString("WelcomeCardContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Book room** : Book your favorite room for a default duration of 30 mins.
        /// </summary>
        public static string WelcomeCardContentPart1 {
            get {
                return ResourceManager.GetString("WelcomeCardContentPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Manage favorites** : Add rooms as favorites to help you to quick book them later.
        /// </summary>
        public static string WelcomeCardContentPart2 {
            get {
                return ResourceManager.GetString("WelcomeCardContentPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string WelcomeCardTitle {
            get {
                return ResourceManager.GetString("WelcomeCardTitle", resourceCulture);
            }
        }
    }
}
